POST https://ticketing.dev/api/users/signin
Content-Type: application/json; charset=UTF-8

{
    "email": "fmwibutsa@gmail.com",
    "password": "Umusatsi@1"
}
###
GET https://ticketing.dev/api/users/current-user
Content-Type: application/json; charset=UTF-8
