apiVersion: skaffold/v4beta14
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mwibutsa/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: mwibutsa/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.{ts,tsx}"
          - dest: .
            src: "public/**/*"
